name: "Terraform Drift Detection"

on:
  schedule:
    - cron: '0 17 * * *' # Runs daily at 10 AM PST
  workflow_dispatch:      # Allows you to run it manually for testing

permissions:
  id-token: write
  contents: read

jobs:
  drift-check:
    name: "Drift Check: ${{ matrix.environment }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev] # Check all your envs
    environment: ${{ matrix.environment }}

    defaults:
      run:
        working-directory: environments/${{ matrix.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Init
        run: rm -rf .terraform && terraform init

      - name: Check for Drift
        id: plan
        run: |
          # Use a temporary file to catch the exit code
          set +e
          terraform plan -detailed-exitcode -no-color
          terraform plan -detailed-exitcode -no-color > drift_output.txt
          EXIT_CODE=$?
          echo "exitcode=$EXIT_CODE"
          echo "exitcode=$EXIT_CODE" >> $GITHUB_OUTPUT
          set -e

          # Optional: Upload the text file so you can download it in the next step
          # or just cat it here if you only need the logs.
        

      - name: Alert on Drift
        if: steps.plan.outputs.exitcode == '2'
        run: |
          echo "### ⚠️ DRIFT DETECTED in ${{ matrix.environment }}!" >> $GITHUB_STEP_SUMMARY
          echo "The following changes were found between code and cloud:" >> $GITHUB_STEP_SUMMARY
          echo '```diff' >> $GITHUB_STEP_SUMMARY
          # This grep pulls only the lines that show the actual resource changes
          grep -E "resource|~|\+|-" drift_output.txt >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

          # Also print to the console for easy viewing in logs
          cat drift_output.txt
