name: "Reusable Linting"

on:
  workflow_call: # This allows other workflows to call this one

jobs:
  lint:
    name: "Run linting"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        run: terraform init -backend=false # No need for actual backend access just to lint

      - name: Terraform Validate
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v6
        with:
          tflint_version: v0.50.0

      - name: Run TFLint
        run: tflint -f compact